---
exclude_paths:
  - 'content/**/*'
  - 'README.md'
  - 'LICENSE'
  - '.github/**/*'
  - '.github/CODE_OF_CONDUCT.md'
  - '.github/pull_request_template.md'
  - '.github/CONTRIBUTING.md'
  - 'src/@narative/**/*'
