name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Yarn Build
      uses: Borales/actions-yarn@1.1.0
      args: install
    - name: Yarn Test
      uses: Borales/actions-yarn@1.1.0
      args: build
    - name: Yarn & Percy CI
      uses: jpvalery/yarn-percy-ci@master
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
