name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1 
    - name: Yarn Install
      run: yarn install
    - name: Yarn Build
      run: yarn build
    - name: Yarn & Percy CI
      uses: jpvalery/yarn-percy-ci@master
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
